# docker-compose.yml
version: "3"
services:
  # webapp: # This is for development.
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.development
  webapp: # This is for production.
    image: adriagarrido/timetracker:latest
    ports:
      - "8080:80"
    links: 
      - database
    # volumes:
    #   - .:/var/www
    environment:
      APACHE_RUN_USER: apache-www-volume
      APACHE_RUN_GROUP: apache-www-volume
      MYSQL_HOSTNAME: database
      MYSQL_DATABASE: myDb
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
  database:
    image: mysql:5.7.13
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
    volumes:
        - ./mysql:/var/lib/mysql
    networks:
        - default